using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Mimiclay;

/// <summary>One row of the material remap table: FBX material name → project material.</summary>
public class FbxMaterialRemap
{
	[KeyProperty] public string FbxMaterial { get; set; }
	[KeyProperty] public Material Material { get; set; }
}

/// <summary>
/// Marks a GameObject as generated by an <see cref="FbxBlockoutImporter"/>, keyed by the FBX
/// object it came from so reimports update it in place (renaming the GameObject is safe).
/// </summary>
public sealed class FbxImportedPiece : Component
{
	[Property, ReadOnly] public string SourceName { get; set; }
}

/// <summary>
/// Live Blender → s&amp;box bridge for level blockouts. Point it at an .fbx inside the Assets
/// folder and it builds a child GameObject per FBX object (ModelRenderer + optional ModelCollider,
/// runtime-built model — no .vmdl compile). It polls the file and reimports the moment Blender
/// re-exports, so alt-tabbing back to s&amp;box shows the new geometry.
///
/// Children persist in the scene and are matched by FBX object name on reimport, so per-child
/// tweaks like ModelRenderer.Tint survive. Transforms always come from the FBX (move things in
/// Blender, not here). Objects deleted in Blender get their children deleted here.
/// </summary>
[Title( "FBX Blockout Importer" )]
[Category( "Level" )]
[Icon( "sync" )]
public sealed class FbxBlockoutImporter : Component, Component.ExecuteInEditor
{
	/// <summary>Path of the .fbx relative to the Assets folder, e.g. "blockout/kitchen.fbx".</summary>
	[Property] public string FbxPath { get; set; } = "";

	/// <summary>Extra multiplier on top of the FBX unit conversion (file units are treated as cm →
	/// converted to inches). At 1 a real-world Blender scene is physically correct (1m → 39.37 units);
	/// set 2.54 if you model with 1 Blender unit = 1 s&amp;box unit.</summary>
	[Property, Range( 0.01f, 100f ) ] public float ImportScale { get; set; } = 1f;

	/// <summary>Build a static ModelCollider per piece from the render geometry.</summary>
	[Property] public bool BuildCollision { get; set; } = true;

	/// <summary>Poll the file and reimport automatically when it changes.</summary>
	[Property, Group( "Auto Reimport" )] public bool AutoReimport { get; set; } = true;

	/// <summary>Seconds between file checks.</summary>
	[Property, Group( "Auto Reimport" ), Range( 0.1f, 5f )] public float CheckInterval { get; set; } = 0.5f;

	/// <summary>Used for FBX materials with no remap entry. Falls back to a dev material.</summary>
	[Property, Group( "Materials" )] public Material DefaultMaterial { get; set; }

	/// <summary>FBX material name → project material. Use "Scan FBX Materials" to fill in the names.</summary>
	[Property, Group( "Materials" )] public List<FbxMaterialRemap> MaterialRemaps { get; set; } = new();

	/// <summary>Shipped-build copy of the geometry, written by "Bake Shippable Geometry". Standalone
	/// builds can't read the raw .fbx (only compiled assets get packaged) and the runtime-built models
	/// save as a dead <c>sbox_procedural_model</c> placeholder — so when the file is missing, the
	/// importer rebuilds its children from this instead.</summary>
	[Property, Group( "Bake" )] public FbxBakedBlockout BakedGeometry { get; set; }

	/// <summary>Editor-only bake hook — writing a .fbxbake asset needs the editor assembly, which game
	/// code can't reference. Wired up by FbxBakeUtility; null at runtime.</summary>
	public static Func<FbxBlockoutImporter, bool> BakeHandler;

	[Property, ReadOnly, Group( "Status" )] public string LastImport { get; set; } = "";

	ulong _importedHash;
	ulong _failedHash;
	bool _usingBake;
	RealTimeSince _sinceCheck;

	protected override void OnEnabled()
	{
		_importedHash = 0;
		_failedHash = 0;
		_usingBake = false;
		TryImport( quiet: false );
	}

	protected override void OnUpdate()
	{
		if ( _usingBake )
			return; // running off the baked asset — there's no file to poll
		if ( !AutoReimport )
			return;
		if ( _sinceCheck < CheckInterval )
			return;

		_sinceCheck = 0;
		TryImport( quiet: true );
	}

	[Button( "Reimport Now" )]
	public void ReimportNow()
	{
		_importedHash = 0;
		_failedHash = 0;
		_usingBake = false;
		TryImport( quiet: false );
	}

	/// <summary>Bake the current FBX into a <see cref="FbxBakedBlockout"/> asset (editor only) so
	/// standalone builds get the geometry — see <see cref="BakedGeometry"/>. Rebake after level
	/// changes; the importer warns when the file drifts from the bake.</summary>
	[Button( "Bake Shippable Geometry" )]
	public void BakeShippable()
	{
		if ( BakeHandler is null )
		{
			Log.Warning( "[FbxBlockout] Baking needs the editor — the bake button only works in the editor, not in game." );
			return;
		}

		BakeHandler( this );
	}

	/// <summary>Read the FBX and add a remap row for every material it references that we don't have yet.</summary>
	[Button( "Scan FBX Materials" )]
	public void ScanMaterials()
	{
		var bytes = ReadFileBytes( out var error );
		if ( bytes == null )
		{
			Log.Warning( $"[FbxBlockout] {error}" );
			return;
		}

		try
		{
			FbxSceneReader.Read( bytes, ImportScale, out var names );
			MaterialRemaps ??= new List<FbxMaterialRemap>();
			var added = 0;
			foreach ( var name in names )
			{
				if ( MaterialRemaps.Any( r => string.Equals( r?.FbxMaterial, name, StringComparison.OrdinalIgnoreCase ) ) )
					continue;
				MaterialRemaps.Add( new FbxMaterialRemap { FbxMaterial = name } );
				added++;
			}
			Log.Info( $"[FbxBlockout] {names.Count} material(s) in file, {added} new remap row(s) added." );
		}
		catch ( Exception e )
		{
			Log.Warning( $"[FbxBlockout] Couldn't scan '{FbxPath}': {e.Message}" );
		}
	}

	// ---------------------------------------------------------------- import

	void TryImport( bool quiet )
	{
		var bytes = ReadFileBytes( out var error );
		if ( bytes == null )
		{
			// shipped build: the raw .fbx isn't in the package — run off the baked asset instead
			if ( BuildFromBake() )
				return;

			if ( !quiet )
			{
				LastImport = error;
				Log.Warning( $"[FbxBlockout] {error}" );
			}
			return;
		}

		var hash = FbxBakedBlockout.HashBytes( bytes );
		if ( hash == _importedHash )
			return;
		if ( hash == _failedHash )
			return; // already failed on this exact content — wait for the next export

		try
		{
			var pieces = FbxSceneReader.Read( bytes, ImportScale, out _ );
			SyncChildren( pieces );
			_importedHash = hash;
			_failedHash = 0;
			_usingBake = false;
			var tris = pieces.Sum( p => p.SubMeshes.Sum( s => s.Vertices.Count ) ) / 3;
			LastImport = $"{pieces.Count} object(s), {tris} tris — {DateTime.Now:HH:mm:ss}";
			Log.Info( $"[FbxBlockout] Imported '{FbxPath}': {LastImport}" );

			if ( BakedGeometry != null && (BakedGeometry.SourceHash != hash || BakedGeometry.ImportScale != ImportScale) )
				Log.Warning( $"[FbxBlockout] '{FbxPath}' has changed since it was baked — hit \"Bake Shippable Geometry\" or standalone builds will ship the old geometry." );
		}
		catch ( Exception e )
		{
			// mid-write reads land here too; the hash changes again once Blender finishes writing
			_failedHash = hash;
			LastImport = $"Import failed: {e.Message}";
			Log.Warning( $"[FbxBlockout] Import of '{FbxPath}' failed: {e.Message}" );
		}
	}

	/// <summary>Rebuild the children from <see cref="BakedGeometry"/> — the standalone path, where
	/// the source .fbx doesn't exist. Idempotent: once built, stays built.</summary>
	bool BuildFromBake()
	{
		if ( _usingBake )
			return true;

		var pieces = BakedGeometry?.UnpackPieces();
		if ( pieces == null )
			return false;

		try
		{
			SyncChildren( pieces );
		}
		catch ( Exception e )
		{
			Log.Warning( $"[FbxBlockout] Building '{FbxPath}' from its bake failed: {e.Message}" );
			return false;
		}

		_usingBake = true;
		LastImport = $"{pieces.Count} object(s) from bake '{BakedGeometry.ResourcePath}'";
		Log.Info( $"[FbxBlockout] {LastImport}" );
		return true;
	}

	void SyncChildren( List<FbxPiece> pieces )
	{
		// existing imported children by source name
		var existing = new Dictionary<string, GameObject>( StringComparer.OrdinalIgnoreCase );
		foreach ( var child in GameObject.Children )
		{
			var marker = child.Components.Get<FbxImportedPiece>( FindMode.EverythingInSelf );
			if ( marker.IsValid() && !string.IsNullOrEmpty( marker.SourceName ) )
				existing[marker.SourceName] = child;
		}

		var kept = new HashSet<string>( StringComparer.OrdinalIgnoreCase );

		foreach ( var piece in pieces )
		{
			kept.Add( piece.Name );

			if ( !existing.TryGetValue( piece.Name, out var go ) || !go.IsValid() )
			{
				go = new GameObject( true, piece.Name );
				go.Parent = GameObject;
				go.Components.Create<FbxImportedPiece>().SourceName = piece.Name;
			}

			go.LocalPosition = piece.Position;
			go.LocalRotation = piece.Rotation;
			go.LocalScale = piece.Scale;

			var model = BuildModel( piece );

			var renderer = go.Components.GetOrCreate<ModelRenderer>();
			renderer.Model = model;

			var collider = go.Components.Get<ModelCollider>( FindMode.EverythingInSelf );
			if ( BuildCollision )
			{
				collider ??= go.Components.Create<ModelCollider>();
				collider.Enabled = true;
				collider.Model = model;
			}
			else
			{
				collider?.Destroy();
			}
		}

		// remove children whose FBX object no longer exists
		foreach ( var (name, go) in existing )
		{
			if ( !kept.Contains( name ) && go.IsValid() )
				go.Destroy();
		}
	}

	Model BuildModel( FbxPiece piece )
	{
		var builder = Model.Builder;

		foreach ( var sub in piece.SubMeshes )
		{
			if ( sub.Vertices.Count == 0 )
				continue;

			var mesh = new Mesh( sub.Material ?? ResolveMaterial( sub.MaterialName ) );
			mesh.CreateVertexBuffer( sub.Vertices.Count, sub.Vertices );

			var indices = new List<int>( sub.Vertices.Count );
			for ( var i = 0; i < sub.Vertices.Count; i++ )
				indices.Add( i );
			mesh.CreateIndexBuffer( indices.Count, indices );
			mesh.Bounds = sub.Bounds;

			builder.AddMesh( mesh );
		}

		if ( BuildCollision && piece.CollisionIndices.Count > 0 )
			builder.AddCollisionMesh( piece.CollisionVertices, piece.CollisionIndices );

		return builder.Create();
	}

	/// <summary>FBX material name → project material via the remap table. Public so the editor-side
	/// bake resolves materials with exactly the same rules.</summary>
	public Material ResolveMaterial( string fbxName )
	{
		var entry = MaterialRemaps?.FirstOrDefault( r =>
			string.Equals( r?.FbxMaterial, fbxName, StringComparison.OrdinalIgnoreCase ) );

		if ( entry?.Material != null )
			return entry.Material;
		if ( DefaultMaterial != null )
			return DefaultMaterial;

		return Material.Load( "materials/dev/reflectivity_30.vmat" );
	}

	// ---------------------------------------------------------------- file access

	/// <summary>Read the source .fbx from the mounted filesystem. Public so the editor-side bake reads
	/// the exact same bytes the live import does. Null (with <paramref name="error"/> set) when the
	/// file is missing — which is every standalone build, since raw .fbx files aren't packaged.</summary>
	public byte[] ReadFileBytes( out string error )
	{
		error = null;

		if ( string.IsNullOrWhiteSpace( FbxPath ) )
		{
			error = "No FBX path set.";
			return null;
		}

		var path = FbxPath.Replace( '\\', '/' ).Trim().TrimStart( '/' );
		if ( path.StartsWith( "assets/", StringComparison.OrdinalIgnoreCase ) )
			path = path.Substring( 7 );

		try
		{
			if ( !FileSystem.Mounted.FileExists( path ) )
			{
				error = $"'{path}' not found in the mounted filesystem (path is relative to Assets).";
				return null;
			}

			using var stream = FileSystem.Mounted.OpenRead( path );
			using var ms = new MemoryStream();
			stream.CopyTo( ms );
			return ms.ToArray();
		}
		catch ( Exception e )
		{
			// Blender may still be writing — treat as transient
			error = $"Couldn't read '{path}': {e.Message}";
			return null;
		}
	}
}
