using System;
using System.Collections.Generic;

namespace Mimiclay;

/// <summary>
/// One entry in a group's palette: the colour the group may be swapped to, and the Metallic/Roughness it
/// wears with it. Every swatch carries a full look — new swatches inherit the group's detected finish, so
/// adding a colour only changes the colour until you move the sliders yourself.
/// </summary>
public class PropColorTint
{
	/// <summary>The colour the group is tinted to. Rolling the group's own detected colour restores the
	/// authored colours exactly (see <see cref="PropColorRandomizer"/>).</summary>
	[Property] public Color Color { get; set; } = Color.White;

	/// <summary>Metalness for the group. Applied as an OFFSET, like the colour tint: each brush keeps its
	/// distance from the group's detected metalness, so per-brush finish variation survives the swap.
	/// Seeded from the group's detected metalness — leave it there for a colour-only swatch.</summary>
	[Property, Range( 0f, 1f )] public float Metallic { get; set; } = 0f;

	/// <summary>Roughness for the group, applied as an offset the same way.</summary>
	[Property, Range( 0f, 1f )] public float Roughness { get; set; } = 1f;

	public PropColorTint Copy() => new()
	{
		Color = Color,
		Metallic = Metallic,
		Roughness = Roughness
	};

	/// <summary>Value equality across every field — the live preview diffs with this.</summary>
	public bool Matches( PropColorTint o ) =>
		o is not null &&
		Color.r == o.Color.r && Color.g == o.Color.g && Color.b == o.Color.b && Color.a == o.Color.a &&
		Metallic == o.Metallic && Roughness == o.Roughness;

	/// <summary>Still at the values the inspector's "+" hands out — i.e. nobody has authored this swatch
	/// yet, so it's safe to stamp the group's detected finish onto it.</summary>
	public bool IsFresh() => Metallic == 0f && Roughness == 1f;
}

/// <summary>
/// One detected colour family on a prop — e.g. "the gold bits", "the pot body", "the polkadots" — plus
/// the palette of variants the randomizer is allowed to swap it to. Filled in by
/// <see cref="PropColorRandomizer.DetectGroups"/>; you then hand-fill <see cref="Variants"/> per group.
/// </summary>
public class PropColorGroup
{
	/// <summary>Display name, generated from the detected look ("Group 1 · #c8a03e · m0.80 r0.30 · 5 brushes").</summary>
	[Property] public string Name { get; set; }

	/// <summary>The group's representative (average) colour as detected — a swatch so you can see which
	/// family this row is. Regenerated by Detect; editing it changes nothing.</summary>
	[Property] public Color Detected { get; set; }

	/// <summary>The group's representative metalness/roughness as detected. Every variant's material is
	/// applied relative to these, and new variants are seeded from them.</summary>
	[Property, ReadOnly] public float DetectedMetallic { get; set; }

	/// <inheritdoc cref="DetectedMetallic"/>
	[Property, ReadOnly] public float DetectedRoughness { get; set; } = 1f;

	/// <summary>The looks this group MAY be randomised to. Detect seeds it with the group's own detected
	/// look (you nearly always want "unchanged" in the pool — rolling that swatch restores the originals
	/// exactly). Empty the list to lock the group (Randomise skips it).</summary>
	[Property] public List<PropColorTint> Variants { get; set; } = new();

	/// <summary>Indices into the sculpture's brush list that belong to this group (filled by Detect).</summary>
	[Property] public List<int> BrushIndices { get; set; } = new();

	// Palettes saved by the colour-only version of this component, kept so old prefabs upgrade instead of
	// losing their hand-filled swatches. Migrated into Variants on first touch, then nulled out.
	[Property, Hide] public List<Color> Tints { get; set; }
}

/// <summary>
/// Authoring helper for prop look variation: sits next to an <see cref="SdfSculpture"/>, groups its
/// brushes into colour families ("Detect Groups"), and can then swap each family to a random variant from
/// a per-group palette ("Randomise") or restore the authored look ("Revert").
///
/// Grouping is HSV-based and deliberately tolerant of VALUE differences, because sculpts fake shading
/// by nudging a shape's brightness — a pot body and its slightly-darker underside should land in one
/// group. Hue+saturation are compared as a distance on the chroma disc (x = s·cos h, y = s·sin h), which
/// also makes hue naturally irrelevant for greys; value is compared separately with its own, looser,
/// tolerance. Tune both with the Detection sliders.
///
/// A variant is a whole look — colour plus Metallic/Roughness — and both halves are applied the same
/// relative way, so the family's internal variation survives a swap: each brush keeps its saturation/value
/// RATIO to the group's detected colour (a family tinted red → blue keeps its darker-underside reading)
/// and its OFFSET from the group's detected finish (a slightly-rougher member stays slightly rougher).
/// Every variant is seeded with the group's detected material, so a swatch you only recolour behaves as a
/// pure tint. Everything is recomputed from the ORIGINAL snapshot taken at Detect, so re-rolling never
/// compounds drift and Revert is exact. The public <see cref="Randomise(Random)"/> overload takes a seeded
/// RNG for the (future) prop-randomisation system.
///
/// While <see cref="LivePreview"/> is on, dragging a swatch or a material slider in the inspector previews
/// it on the prop live — the variant lists are diffed per editor frame, since the inspector offers no
/// change callback.
/// </summary>
[Title( "Prop Color Randomizer" )]
[Category( "SDF" )]
[Icon( "palette" )]
public sealed class PropColorRandomizer : Component, Component.ExecuteInEditor
{
	/// <summary>The sculpture whose brushes get grouped/tinted. Defaults to one on this GameObject.</summary>
	[Property] public SdfSculpture Sculpture { get; set; }

	/// <summary>How far apart two colours may sit on the hue/saturation disc (radius 1) and still merge
	/// into one group. Bigger = fewer, broader groups. ~0.08 splits close hues (gold vs yellow); ~0.3
	/// merges most colourful things together.</summary>
	[Property, Range( 0.02f, 0.5f ), Group( "Detection" )] public float ChromaTolerance { get; set; } = 0.15f;

	/// <summary>How different two colours' BRIGHTNESS may be and still merge. Kept deliberately loose so
	/// fake-shading variants (same colour, nudged darker/lighter) fold into their parent group.</summary>
	[Property, Range( 0.05f, 1f ), Group( "Detection" )] public float ValueTolerance { get; set; } = 0.35f;

	/// <summary>Also require similar Metallic/Roughness to group — keeps a metallic gold rim out of a
	/// matte yellow group even when their colours match.</summary>
	[Property, Group( "Detection" )] public bool SplitByMaterial { get; set; } = true;

	/// <summary>Preview variant edits on the prop itself: while you drag a group's swatch or its
	/// Metallic/Roughness sliders, that look is applied to the group live. The prop keeps showing the last
	/// previewed look when you're done — Revert (or Randomise) to move on. Editor only.</summary>
	[Property, Group( "Preview" )] public bool LivePreview { get; set; } = true;

	/// <summary>The detected colour families. Fill each group's Variants with the looks it may roll to;
	/// a group with no variants is locked and never changes.</summary>
	[Property, Group( "Groups" )] public List<PropColorGroup> Groups { get; set; } = new();

	// The authored look, snapshotted at Detect, one entry per brush — Randomise derives from these (never
	// from the current, possibly-already-randomised values) and Revert restores them. Serialised (Hide,
	// not fields) so a prefab saved mid-randomise can still revert. The material lists are healed from the
	// live brushes when missing, so prefabs saved by the colour-only version still work.
	[Property, Hide] public List<Color> OriginalColors { get; set; } = new();
	[Property, Hide] public List<float> OriginalMetallic { get; set; } = new();
	[Property, Hide] public List<float> OriginalRoughness { get; set; } = new();

	// AUTHORED brush count at Detect time — a cheap guard so a sculpt edited after detection (indices now
	// stale) warns instead of tinting the wrong brushes. Authored, not total, so runtime damage craters
	// (appended to the brush tail) don't invalidate a detection the future prop-randomiser wants to roll.
	[Property, Hide] public int DetectedBrushCount { get; set; }

	const float MaterialTolerance = 0.25f;

	// Last-seen copy of every group's variant list, for the live preview: the inspector writes straight
	// into the [Property] lists with no callback, so we diff per editor frame and treat a change on an
	// existing variant as "the user is editing this look right now".
	List<List<PropColorTint>> _variantShadow;
	// Per-group variant counts, tracked whether or not the preview runs, so a swatch added with the
	// inspector's "+" can be seeded with the group's finish the frame it appears.
	List<int> _variantCounts;
	bool _previewDirty;
	RealTimeSince _sincePreviewChange;

	protected override void OnUpdate()
	{
		if ( !Scene.IsEditor )
			return;

		UpgradeLegacy();
		SeedNewVariants();

		if ( !LivePreview )
			return;

		ScanVariantPreview();

		// The raymarcher self-refreshes from brush data, so the drag previews live with no meshing;
		// one Rebuild after the picking settles syncs the mesh/collider path too.
		if ( _previewDirty && _sincePreviewChange > 0.4f )
		{
			_previewDirty = false;
			if ( Sculpture.IsValid() )
				Sculpture.Rebuild();
		}
	}

	// The inspector's "+" hands out a bare PropColorTint (white, metal 0, rough 1) — a swatch that would
	// strip a metallic family's finish the moment it rolled. A newly appeared entry inherits the group's
	// detected material instead, so adding a colour only ever changes the colour. Only entries still at
	// those construction defaults are stamped, so a duplicated or hand-authored swatch is left alone.
	void SeedNewVariants()
	{
		if ( Groups is not { Count: > 0 } )
		{
			_variantCounts = null;
			return;
		}

		bool known = _variantCounts is not null && _variantCounts.Count == Groups.Count;

		var counts = new List<int>( Groups.Count );
		for ( int g = 0; g < Groups.Count; g++ )
		{
			var group = Groups[g];
			var variants = group?.Variants;
			int count = variants?.Count ?? 0;
			counts.Add( count );

			if ( !known || count <= _variantCounts[g] )
				continue;

			foreach ( var v in variants )
				if ( v is not null && v.IsFresh() )
				{
					v.Metallic = group.DetectedMetallic;
					v.Roughness = group.DetectedRoughness;
				}
		}

		_variantCounts = counts;
	}

	void ScanVariantPreview()
	{
		if ( Groups is not { Count: > 0 } )
		{
			_variantShadow = null;
			return;
		}

		// Structural change (first frame, groups or variants added/removed): resync WITHOUT previewing —
		// a freshly added variant is a look nobody picked.
		bool structural = _variantShadow is null || _variantShadow.Count != Groups.Count;
		if ( !structural )
			for ( int g = 0; g < Groups.Count && !structural; g++ )
				structural = (Groups[g].Variants?.Count ?? 0) != _variantShadow[g].Count;

		if ( structural )
		{
			_variantShadow = new List<List<PropColorTint>>( Groups.Count );
			foreach ( var grp in Groups )
			{
				var copy = new List<PropColorTint>();
				if ( grp.Variants is not null )
					foreach ( var v in grp.Variants )
						copy.Add( v?.Copy() ?? new PropColorTint() );
				_variantShadow.Add( copy );
			}
			return;
		}

		int pickedGroup = -1;
		PropColorTint picked = null;
		for ( int g = 0; g < Groups.Count; g++ )
		{
			var variants = Groups[g].Variants;
			if ( variants is null )
				continue;
			var shadow = _variantShadow[g];
			for ( int i = 0; i < variants.Count; i++ )
			{
				var v = variants[i];
				if ( v is null || v.Matches( shadow[i] ) )
					continue;
				pickedGroup = g;
				picked = v;
				shadow[i] = v.Copy();
			}
		}

		if ( pickedGroup < 0 || !SnapshotValid() )
			return;

		ApplyVariant( Groups[pickedGroup], picked );
		_previewDirty = true;
		_sincePreviewChange = 0;
	}

	static bool SameColor( Color a, Color b ) => a.r == b.r && a.g == b.g && a.b == b.b && a.a == b.a;

	/// <summary>Scan the sculpture's brushes and rebuild <see cref="Groups"/> from the current tolerances.
	/// Existing palettes are carried over to the nearest matching new group so re-detecting after a
	/// sensitivity tweak doesn't throw your palettes away. Reverts first if the prop is randomised, so the
	/// snapshot is always the authored base.</summary>
	[Button( "Detect Groups" )]
	public void DetectGroups()
	{
		if ( !ResolveSculpture() )
			return;

		UpgradeLegacy();

		// Never snapshot a randomised look as "the original": restore first if we have a valid snapshot.
		if ( SnapshotValid() )
			ApplyOriginals();

		var brushes = Sculpture.Brushes;
		int authored = Sculpture.AuthoredBrushCount; // skip the damage tail — craters aren't authored colour

		OriginalColors = new List<Color>( authored );
		OriginalMetallic = new List<float>( authored );
		OriginalRoughness = new List<float>( authored );
		for ( int i = 0; i < authored; i++ )
		{
			OriginalColors.Add( brushes[i].Color );
			OriginalMetallic.Add( brushes[i].Metallic );
			OriginalRoughness.Add( brushes[i].Roughness );
		}
		DetectedBrushCount = authored;

		var oldGroups = Groups;
		Groups = new List<PropColorGroup>();

		// Greedy clustering against running group centroids: each brush joins the closest group within
		// tolerance, else starts a new one. Centroids live in (chroma-x, chroma-y, value) space and carry
		// the running mean material, which becomes the group's detected finish.
		var centroids = new List<(float x, float y, float v, float metal, float rough, int n)>();
		for ( int i = 0; i < authored; i++ )
		{
			var b = brushes[i];
			var (x, y, v) = ChromaPoint( b.Color );

			int best = -1;
			float bestDist = float.MaxValue;
			for ( int g = 0; g < centroids.Count; g++ )
			{
				var c = centroids[g];
				float dx = x - c.x, dy = y - c.y;
				float chroma = MathF.Sqrt( dx * dx + dy * dy );
				if ( chroma > ChromaTolerance || MathF.Abs( v - c.v ) > ValueTolerance )
					continue;
				if ( SplitByMaterial &&
					(MathF.Abs( b.Metallic - c.metal ) > MaterialTolerance ||
					 MathF.Abs( b.Roughness - c.rough ) > MaterialTolerance) )
					continue;
				if ( chroma < bestDist )
				{
					bestDist = chroma;
					best = g;
				}
			}

			if ( best < 0 )
			{
				centroids.Add( (x, y, v, b.Metallic, b.Roughness, 1) );
				Groups.Add( new PropColorGroup { BrushIndices = { i } } );
			}
			else
			{
				var c = centroids[best];
				float n = c.n + 1;
				centroids[best] = ((c.x * c.n + x) / n, (c.y * c.n + y) / n, (c.v * c.n + v) / n,
					(c.metal * c.n + b.Metallic) / n, (c.rough * c.n + b.Roughness) / n, c.n + 1);
				Groups[best].BrushIndices.Add( i );
			}
		}

		// Biggest families first, then name each from its centroid and rescue any old palette whose
		// detected colour still matches a new group.
		var order = new List<int>();
		for ( int g = 0; g < Groups.Count; g++ )
			order.Add( g );
		order.Sort( ( a, b ) => Groups[b].BrushIndices.Count.CompareTo( Groups[a].BrushIndices.Count ) );

		var sorted = new List<PropColorGroup>( Groups.Count );
		foreach ( int g in order )
		{
			var grp = Groups[g];
			var c = centroids[g];
			float sat = MathF.Sqrt( c.x * c.x + c.y * c.y );
			float hue = MathF.Atan2( c.y, c.x ) * (180f / MathF.PI);
			grp.Detected = ClayLook.HsvToRgb( hue, sat, c.v );
			grp.DetectedMetallic = c.metal;
			grp.DetectedRoughness = c.rough;
			grp.Name = $"Group {sorted.Count + 1} · {Hex( grp.Detected )} · {MaterialLabel( c.metal, c.rough )}{grp.BrushIndices.Count} brush{(grp.BrushIndices.Count == 1 ? "" : "es")}";
			grp.Variants = RescueVariants( oldGroups, grp );
			if ( grp.Variants.Count == 0 )
				grp.Variants.Add( new PropColorTint // seed with the original — you nearly always want it in the pool
				{
					Color = grp.Detected,
					Metallic = c.metal,
					Roughness = c.rough
				} );
			sorted.Add( grp );
		}
		Groups = sorted;
		// Groups reordered — resync both shadows before they misread a rescued palette as an edit.
		_variantShadow = null;
		_variantCounts = null;

		Log.Info( $"Prop Color Randomizer: {Groups.Count} colour group(s) across {authored} brush(es)." );
	}

	/// <summary>Roll every group with a non-empty palette to a random variant (editor button —
	/// unseeded). Rebuilds the sculpture. Distinct name (not an overload of <see cref="Randomise"/>) so
	/// the inspector's button reflection can't pick the wrong method.</summary>
	[Button( "Randomise Colors" )]
	public void RandomiseColors() => Randomise( Game.Random );

	/// <summary>Roll with a caller-supplied RNG — the hook for the prop-randomisation system, which can
	/// pass a seeded <see cref="Random"/> so every machine rolls the same look. Returns false (having
	/// said why) when the prop isn't ready to roll, so a scene-wide driver can report what it skipped.</summary>
	public bool Randomise( Random rng )
	{
		if ( !ResolveSculpture() || !RequireValidSnapshot() )
			return false;

		foreach ( var group in Groups )
		{
			if ( group.Variants is not { Count: > 0 } variants )
				continue; // no palette = locked group

			ApplyVariant( group, variants[rng.Next( variants.Count )] );
		}

		Sculpture.Rebuild();
		return true;
	}

	/// <summary>Restore the authored look (editor button). Distinct name from <see cref="Revert"/> so the
	/// inspector's button reflection can't pick the bool-returning one.</summary>
	[Button( "Revert Colors" )]
	public void RevertColors() => Revert();

	/// <summary>Restore every brush to the colour and material snapshotted at Detect. Rebuilds the
	/// sculpture. Returns false (having said why) when there's nothing valid to restore.</summary>
	public bool Revert()
	{
		if ( !ResolveSculpture() || !RequireValidSnapshot() )
			return false;

		ApplyOriginals();
		Sculpture.Rebuild();
		return true;
	}

	// Apply one variant to a group. Colour: shift every member to the variant's hue, scaling saturation
	// and value by each brush's ratio to the group's detected colour — so fake shading (a darker/lighter
	// sibling) keeps its offset in the new colour. Material: offset from the group's detected finish, so a
	// slightly-rougher member stays slightly rougher, and a variant left at the detected material lands
	// back on the authored values exactly. Everything reads the ORIGINAL snapshot, never the current
	// values, so re-rolling can't compound.
	void ApplyVariant( PropColorGroup group, PropColorTint variant )
	{
		if ( variant is null )
			return;

		var brushes = Sculpture.Brushes;

		// Rolling (or previewing) the group's own detected swatch means "keep the original colour" —
		// restore the snapshot exactly rather than tinting, which would snap every member to one hue and
		// flatten any slight hue variation inside the group.
		bool keepColor = SameColor( variant.Color, group.Detected );

		var (_, gs, gv) = ClayLook.RgbToHsv( group.Detected );
		var (th, ts, tv) = ClayLook.RgbToHsv( variant.Color );

		foreach ( int i in group.BrushIndices )
		{
			if ( i < 0 || i >= brushes.Count || i >= OriginalColors.Count )
				continue;

			var original = OriginalColors[i];

			if ( keepColor )
			{
				brushes[i].Color = original;
			}
			else
			{
				var (_, bs, bv) = ClayLook.RgbToHsv( original );

				// Ratio to the group representative; a near-zero representative channel degenerates to 1
				// (no offset to preserve).
				float satRatio = gs > 1e-3f ? bs / gs : 1f;
				float valRatio = gv > 1e-3f ? bv / gv : 1f;

				var tinted = ClayLook.HsvToRgb( th,
					Math.Clamp( ts * satRatio, 0f, 1f ),
					Math.Clamp( tv * valRatio, 0f, 1f ) );
				brushes[i].Color = tinted.WithAlpha( original.a );
			}

			if ( i >= OriginalMetallic.Count || i >= OriginalRoughness.Count )
				continue;

			brushes[i].Metallic = Math.Clamp( variant.Metallic + (OriginalMetallic[i] - group.DetectedMetallic), 0f, 1f );
			brushes[i].Roughness = Math.Clamp( variant.Roughness + (OriginalRoughness[i] - group.DetectedRoughness), 0f, 1f );
		}
	}

	void ApplyOriginals()
	{
		var brushes = Sculpture.Brushes;
		int n = Math.Min( brushes.Count, OriginalColors.Count );
		for ( int i = 0; i < n; i++ )
		{
			brushes[i].Color = OriginalColors[i];
			if ( i < OriginalMetallic.Count )
				brushes[i].Metallic = OriginalMetallic[i];
			if ( i < OriginalRoughness.Count )
				brushes[i].Roughness = OriginalRoughness[i];
		}
	}

	// Bring a prop saved by the colour-only version up to date. That version never wrote Metallic or
	// Roughness, so whatever the brushes wear now IS the authored finish: adopt it as the snapshot, average
	// each group's detected finish from it, and give every legacy swatch that same finish — so an upgraded
	// prop rolls exactly as it did before, and its palette is editable from there.
	void UpgradeLegacy()
	{
		if ( !Sculpture.IsValid() )
			return;

		int n = OriginalColors?.Count ?? 0;
		bool needMaterial = n > 0 && (OriginalMetallic is not { } m || m.Count != n ||
			OriginalRoughness is not { } r || r.Count != n);

		bool needPalettes = false;
		if ( Groups is not null )
			foreach ( var group in Groups )
				needPalettes |= group?.Tints is { Count: > 0 };

		if ( !needMaterial && !needPalettes )
			return;

		var brushes = Sculpture.Brushes;

		if ( needMaterial )
		{
			OriginalMetallic = new List<float>( n );
			OriginalRoughness = new List<float>( n );
			for ( int i = 0; i < n; i++ )
			{
				OriginalMetallic.Add( i < brushes.Count ? brushes[i].Metallic : 0f );
				OriginalRoughness.Add( i < brushes.Count ? brushes[i].Roughness : 1f );
			}
		}

		if ( Groups is null )
			return;

		foreach ( var group in Groups )
		{
			if ( group is null )
				continue;

			// Detected material was never saved either — average the group's brushes for it.
			if ( needMaterial && group.BrushIndices is { Count: > 0 } indices )
			{
				float metal = 0f, rough = 0f;
				int count = 0;
				foreach ( int i in indices )
				{
					if ( i < 0 || i >= brushes.Count )
						continue;
					metal += brushes[i].Metallic;
					rough += brushes[i].Roughness;
					count++;
				}
				if ( count > 0 )
				{
					group.DetectedMetallic = metal / count;
					group.DetectedRoughness = rough / count;
				}
			}

			if ( group.Tints is not { Count: > 0 } legacy )
				continue;

			group.Variants ??= new List<PropColorTint>();
			if ( group.Variants.Count == 0 )
				foreach ( var c in legacy )
					group.Variants.Add( new PropColorTint
					{
						Color = c,
						Metallic = group.DetectedMetallic,
						Roughness = group.DetectedRoughness
					} );

			group.Tints = null;
			_variantShadow = null;
			_variantCounts = null;
		}
	}

	static string Hex( Color c ) =>
		$"#{(int)(Math.Clamp( c.r, 0f, 1f ) * 255):x2}{(int)(Math.Clamp( c.g, 0f, 1f ) * 255):x2}{(int)(Math.Clamp( c.b, 0f, 1f ) * 255):x2}";

	// Only worth naming when the family isn't plain matte clay — keeps the common case's name short.
	static string MaterialLabel( float metal, float rough ) =>
		metal > 0.05f || rough < 0.95f ? $"m{metal:0.00} r{rough:0.00} · " : "";

	// A colour's position on the chroma disc (radius = saturation, angle = hue) plus its value. Greys
	// collapse to the disc centre, so hue differences between them cost nothing — exactly what we want.
	static (float x, float y, float v) ChromaPoint( Color c )
	{
		var (h, s, v) = ClayLook.RgbToHsv( c );
		float rad = h * (MathF.PI / 180f);
		return (s * MathF.Cos( rad ), s * MathF.Sin( rad ), v);
	}

	// Re-detecting shouldn't nuke hand-filled palettes: carry a palette over when an old group's detected
	// colour is close (chroma disc + value, same tolerances) to the new group's. Swatches that sat at the
	// old group's detected material follow the NEW one, so "unchanged" stays unchanged after a re-detect.
	List<PropColorTint> RescueVariants( List<PropColorGroup> oldGroups, PropColorGroup target )
	{
		if ( oldGroups is null )
			return new List<PropColorTint>();

		var (x, y, v) = ChromaPoint( target.Detected );
		foreach ( var old in oldGroups )
		{
			if ( old?.Variants is not { Count: > 0 } variants )
				continue;
			var (ox, oy, ov) = ChromaPoint( old.Detected );
			float dx = x - ox, dy = y - oy;
			if ( MathF.Sqrt( dx * dx + dy * dy ) > ChromaTolerance || MathF.Abs( v - ov ) > ValueTolerance )
				continue;

			var copy = new List<PropColorTint>( variants.Count );
			foreach ( var t in variants )
			{
				var c = t?.Copy() ?? new PropColorTint();
				if ( c.Metallic == old.DetectedMetallic && c.Roughness == old.DetectedRoughness )
				{
					c.Metallic = target.DetectedMetallic;
					c.Roughness = target.DetectedRoughness;
				}
				copy.Add( c );
			}
			return copy;
		}
		return new List<PropColorTint>();
	}

	bool ResolveSculpture()
	{
		Sculpture ??= GameObject.Components.Get<SdfSculpture>();
		if ( Sculpture.IsValid() )
			return true;
		Log.Warning( $"{Which}: no SdfSculpture assigned (or on this object)." );
		return false;
	}

	bool SnapshotValid() =>
		Sculpture.IsValid() && OriginalColors is { Count: > 0 } && Sculpture.AuthoredBrushCount == DetectedBrushCount;

	bool RequireValidSnapshot()
	{
		UpgradeLegacy();

		if ( Groups is not { Count: > 0 } || OriginalColors is not { Count: > 0 } )
		{
			Log.Warning( $"{Which}: no groups detected yet — press Detect Groups first." );
			return false;
		}
		if ( Sculpture.AuthoredBrushCount != DetectedBrushCount )
		{
			Log.Warning( $"{Which}: brush list changed since detection ({Sculpture.AuthoredBrushCount} authored now, {DetectedBrushCount} at detect) — re-run Detect Groups." );
			return false;
		}
		return true;
	}

	// Warnings name the prop: a scene-wide Randomise All can trip several at once, and "which one?" is
	// the only question you have when it does.
	string Which => $"Prop Color Randomizer ({GameObject?.Name ?? "?"})";
}
