using System;
using System.Collections.Generic;

namespace Mimiclay;

/// <summary>
/// One detected colour family on a prop — e.g. "the gold bits", "the pot body", "the polkadots" — plus
/// the palette of tints the randomizer is allowed to swap it to. Filled in by
/// <see cref="PropColorRandomizer.DetectGroups"/>; you then hand-fill <see cref="Tints"/> per group.
/// </summary>
public class PropColorGroup
{
	/// <summary>Display name, generated from the detected colour ("Group 1 · #c8a03e · 5 brushes").</summary>
	[Property] public string Name { get; set; }

	/// <summary>The group's representative (average) colour as detected — a swatch so you can see which
	/// family this row is. Regenerated by Detect; editing it changes nothing.</summary>
	[Property] public Color Detected { get; set; }

	/// <summary>The colours this group MAY be randomised to. Detect seeds it with the group's own
	/// detected colour (you nearly always want "unchanged" in the pool — rolling that swatch restores
	/// the originals exactly). Empty the list to lock the group (Randomise skips it).</summary>
	[Property] public List<Color> Tints { get; set; } = new();

	/// <summary>Indices into the sculpture's brush list that belong to this group (filled by Detect).</summary>
	[Property] public List<int> BrushIndices { get; set; } = new();
}

/// <summary>
/// Authoring helper for prop colour variation: sits next to an <see cref="SdfSculpture"/>, groups its
/// brushes into colour families ("Detect Groups"), and can then swap each family to a random tint from
/// a per-group palette ("Randomise") or restore the authored colours ("Revert").
///
/// Grouping is HSV-based and deliberately tolerant of VALUE differences, because sculpts fake shading
/// by nudging a shape's brightness — a pot body and its slightly-darker underside should land in one
/// group. Hue+saturation are compared as a distance on the chroma disc (x = s·cos h, y = s·sin h), which
/// also makes hue naturally irrelevant for greys; value is compared separately with its own, looser,
/// tolerance. Tune both with the Detection sliders.
///
/// Randomise preserves that fake shading: each brush keeps its saturation/value RATIO relative to the
/// group's detected colour, so a family tinted from red to blue keeps its darker-underside reading.
/// Colours are always recomputed from the ORIGINAL snapshot (taken at Detect), so re-rolling never
/// compounds drift, and Revert is exact. The public <see cref="Randomise(Random)"/> overload takes a
/// seeded RNG for the (future) prop-randomisation system.
///
/// Each group's tint palette is seeded with its own detected colour (rolling that swatch restores the
/// originals exactly), and while <see cref="LivePreview"/> is on, dragging a swatch in the colour picker
/// previews it on the prop live — the tint lists are diffed per editor frame, since the inspector offers
/// no change callback.
/// </summary>
[Title( "Prop Color Randomizer" )]
[Category( "SDF" )]
[Icon( "palette" )]
public sealed class PropColorRandomizer : Component, Component.ExecuteInEditor
{
	/// <summary>The sculpture whose brushes get grouped/tinted. Defaults to one on this GameObject.</summary>
	[Property] public SdfSculpture Sculpture { get; set; }

	/// <summary>How far apart two colours may sit on the hue/saturation disc (radius 1) and still merge
	/// into one group. Bigger = fewer, broader groups. ~0.08 splits close hues (gold vs yellow); ~0.3
	/// merges most colourful things together.</summary>
	[Property, Range( 0.02f, 0.5f ), Group( "Detection" )] public float ChromaTolerance { get; set; } = 0.15f;

	/// <summary>How different two colours' BRIGHTNESS may be and still merge. Kept deliberately loose so
	/// fake-shading variants (same colour, nudged darker/lighter) fold into their parent group.</summary>
	[Property, Range( 0.05f, 1f ), Group( "Detection" )] public float ValueTolerance { get; set; } = 0.35f;

	/// <summary>Also require similar Metallic/Roughness to group — keeps a metallic gold rim out of a
	/// matte yellow group even when their colours match.</summary>
	[Property, Group( "Detection" )] public bool SplitByMaterial { get; set; } = true;

	/// <summary>Preview tint edits on the prop itself: while you drag a group's swatch in the colour
	/// picker, that colour is applied to the group live. The prop keeps showing the last previewed
	/// colour when you're done — Revert (or Randomise) to move on. Editor only.</summary>
	[Property, Group( "Preview" )] public bool LivePreview { get; set; } = true;

	/// <summary>The detected colour families. Fill each group's Tints with the colours it may roll to;
	/// a group with no tints is locked and never changes.</summary>
	[Property, Group( "Groups" )] public List<PropColorGroup> Groups { get; set; } = new();

	// The authored colours, snapshotted at Detect, one per brush — Randomise derives from these (never
	// from the current, possibly-already-randomised colours) and Revert restores them. Serialised (Hide,
	// not a field) so a prefab saved mid-randomise can still revert.
	[Property, Hide] public List<Color> OriginalColors { get; set; } = new();

	// AUTHORED brush count at Detect time — a cheap guard so a sculpt edited after detection (indices now
	// stale) warns instead of tinting the wrong brushes. Authored, not total, so runtime damage craters
	// (appended to the brush tail) don't invalidate a detection the future prop-randomiser wants to roll.
	[Property, Hide] public int DetectedBrushCount { get; set; }

	const float MaterialTolerance = 0.25f;

	// Last-seen copy of every group's tint list, for the live preview: the inspector's colour picker
	// writes straight into the [Property] lists with no callback, so we diff per editor frame and treat
	// a VALUE change on an existing swatch as "the user is picking this colour right now".
	List<List<Color>> _tintShadow;
	bool _previewDirty;
	RealTimeSince _sincePreviewChange;

	protected override void OnUpdate()
	{
		if ( !Scene.IsEditor || !LivePreview )
			return;

		ScanTintPreview();

		// The raymarcher self-refreshes from brush colours, so the drag previews live with no meshing;
		// one Rebuild after the picking settles syncs the mesh/collider path too.
		if ( _previewDirty && _sincePreviewChange > 0.4f )
		{
			_previewDirty = false;
			if ( Sculpture.IsValid() )
				Sculpture.Rebuild();
		}
	}

	void ScanTintPreview()
	{
		if ( Groups is not { Count: > 0 } )
		{
			_tintShadow = null;
			return;
		}

		// Structural change (first frame, groups or swatches added/removed): resync WITHOUT previewing —
		// a freshly added swatch starts at a default colour nobody picked.
		bool structural = _tintShadow is null || _tintShadow.Count != Groups.Count;
		if ( !structural )
			for ( int g = 0; g < Groups.Count && !structural; g++ )
				structural = (Groups[g].Tints?.Count ?? 0) != _tintShadow[g].Count;

		if ( structural )
		{
			_tintShadow = new List<List<Color>>( Groups.Count );
			foreach ( var grp in Groups )
				_tintShadow.Add( grp.Tints is null ? new List<Color>() : new List<Color>( grp.Tints ) );
			return;
		}

		int pickedGroup = -1;
		Color picked = default;
		for ( int g = 0; g < Groups.Count; g++ )
		{
			var tints = Groups[g].Tints;
			if ( tints is null )
				continue;
			var shadow = _tintShadow[g];
			for ( int i = 0; i < tints.Count; i++ )
			{
				if ( SameColor( tints[i], shadow[i] ) )
					continue;
				pickedGroup = g;
				picked = tints[i];
				shadow[i] = tints[i];
			}
		}

		if ( pickedGroup < 0 || !Sculpture.IsValid() || !SnapshotValid() )
			return;

		ApplyTint( Groups[pickedGroup], picked );
		_previewDirty = true;
		_sincePreviewChange = 0;
	}

	static bool SameColor( Color a, Color b ) => a.r == b.r && a.g == b.g && a.b == b.b && a.a == b.a;

	/// <summary>Scan the sculpture's brushes and rebuild <see cref="Groups"/> from the current tolerances.
	/// Existing tint palettes are carried over to the nearest matching new group so re-detecting after a
	/// sensitivity tweak doesn't throw your palettes away. Reverts first if colours are randomised, so the
	/// snapshot is always the authored base.</summary>
	[Button( "Detect Groups" )]
	public void DetectGroups()
	{
		if ( !ResolveSculpture() )
			return;

		// Never snapshot randomised colours as "the original": restore first if we have a valid snapshot.
		if ( SnapshotValid() )
			ApplyOriginals();

		var brushes = Sculpture.Brushes;
		int authored = Sculpture.AuthoredBrushCount; // skip the damage tail — craters aren't authored colour

		OriginalColors = new List<Color>( authored );
		for ( int i = 0; i < authored; i++ )
			OriginalColors.Add( brushes[i].Color );
		DetectedBrushCount = authored;

		var oldGroups = Groups;
		Groups = new List<PropColorGroup>();

		// Greedy clustering against running group centroids: each brush joins the closest group within
		// tolerance, else starts a new one. Centroids live in (chroma-x, chroma-y, value) space.
		var centroids = new List<(float x, float y, float v, float metal, float rough, int n)>();
		for ( int i = 0; i < authored; i++ )
		{
			var b = brushes[i];
			var (x, y, v) = ChromaPoint( b.Color );

			int best = -1;
			float bestDist = float.MaxValue;
			for ( int g = 0; g < centroids.Count; g++ )
			{
				var c = centroids[g];
				float dx = x - c.x, dy = y - c.y;
				float chroma = MathF.Sqrt( dx * dx + dy * dy );
				if ( chroma > ChromaTolerance || MathF.Abs( v - c.v ) > ValueTolerance )
					continue;
				if ( SplitByMaterial &&
					(MathF.Abs( b.Metallic - c.metal ) > MaterialTolerance ||
					 MathF.Abs( b.Roughness - c.rough ) > MaterialTolerance) )
					continue;
				if ( chroma < bestDist )
				{
					bestDist = chroma;
					best = g;
				}
			}

			if ( best < 0 )
			{
				centroids.Add( (x, y, v, b.Metallic, b.Roughness, 1) );
				Groups.Add( new PropColorGroup { BrushIndices = { i } } );
			}
			else
			{
				var c = centroids[best];
				float n = c.n + 1;
				centroids[best] = ((c.x * c.n + x) / n, (c.y * c.n + y) / n, (c.v * c.n + v) / n,
					(c.metal * c.n + b.Metallic) / n, (c.rough * c.n + b.Roughness) / n, c.n + 1);
				Groups[best].BrushIndices.Add( i );
			}
		}

		// Biggest families first, then name each from its centroid and rescue any old palette whose
		// detected colour still matches a new group.
		var order = new List<int>();
		for ( int g = 0; g < Groups.Count; g++ )
			order.Add( g );
		order.Sort( ( a, b ) => Groups[b].BrushIndices.Count.CompareTo( Groups[a].BrushIndices.Count ) );

		var sorted = new List<PropColorGroup>( Groups.Count );
		foreach ( int g in order )
		{
			var grp = Groups[g];
			var c = centroids[g];
			float sat = MathF.Sqrt( c.x * c.x + c.y * c.y );
			float hue = MathF.Atan2( c.y, c.x ) * (180f / MathF.PI);
			grp.Detected = ClayLook.HsvToRgb( hue, sat, c.v );
			grp.Name = $"Group {sorted.Count + 1} · {Hex( grp.Detected )} · {grp.BrushIndices.Count} brush{(grp.BrushIndices.Count == 1 ? "" : "es")}";
			grp.Tints = RescueTints( oldGroups, grp.Detected );
			if ( grp.Tints.Count == 0 )
				grp.Tints.Add( grp.Detected ); // seed with the original — you nearly always want it in the pool
			sorted.Add( grp );
		}
		Groups = sorted;
		_tintShadow = null; // groups reordered — resync the preview diff before it misreads a rescued palette

		Log.Info( $"Prop Color Randomizer: {Groups.Count} colour group(s) across {authored} brush(es)." );
	}

	/// <summary>Roll every group with a non-empty tint palette to a random entry (editor button —
	/// unseeded). Rebuilds the sculpture. Distinct name (not an overload of <see cref="Randomise"/>) so
	/// the inspector's button reflection can't pick the wrong method.</summary>
	[Button( "Randomise Colors" )]
	public void RandomiseColors() => Randomise( Game.Random );

	/// <summary>Roll with a caller-supplied RNG — the hook for the prop-randomisation system, which can
	/// pass a seeded <see cref="Random"/> so every machine rolls the same look.</summary>
	public void Randomise( Random rng )
	{
		if ( !ResolveSculpture() || !RequireValidSnapshot() )
			return;

		foreach ( var group in Groups )
		{
			if ( group.Tints is not { Count: > 0 } tints )
				continue; // no palette = locked group

			ApplyTint( group, tints[rng.Next( tints.Count )] );
		}

		Sculpture.Rebuild();
	}

	/// <summary>Restore every brush to the colours snapshotted at Detect. Rebuilds the sculpture.</summary>
	[Button( "Revert Colors" )]
	public void Revert()
	{
		if ( !ResolveSculpture() || !RequireValidSnapshot() )
			return;

		ApplyOriginals();
		Sculpture.Rebuild();
	}

	// Tint one group: shift every member to the target's hue, scaling saturation and value by each
	// brush's ratio to the group's detected colour — so fake shading (a darker/lighter sibling) keeps
	// its offset in the new colour. Ratios come from the ORIGINAL snapshot, never the current colours.
	void ApplyTint( PropColorGroup group, Color target )
	{
		var brushes = Sculpture.Brushes;

		// Rolling (or previewing) the group's own detected swatch means "keep the original" — restore the
		// snapshot exactly rather than tinting, which would snap every member to one hue and flatten any
		// slight hue variation inside the group.
		if ( SameColor( target, group.Detected ) )
		{
			foreach ( int i in group.BrushIndices )
				if ( i >= 0 && i < brushes.Count && i < OriginalColors.Count )
					brushes[i].Color = OriginalColors[i];
			return;
		}

		var (_, gs, gv) = ClayLook.RgbToHsv( group.Detected );
		var (th, ts, tv) = ClayLook.RgbToHsv( target );

		foreach ( int i in group.BrushIndices )
		{
			if ( i < 0 || i >= brushes.Count || i >= OriginalColors.Count )
				continue;

			var original = OriginalColors[i];
			var (_, bs, bv) = ClayLook.RgbToHsv( original );

			// Ratio to the group representative; a near-zero representative channel degenerates to 1
			// (no offset to preserve).
			float satRatio = gs > 1e-3f ? bs / gs : 1f;
			float valRatio = gv > 1e-3f ? bv / gv : 1f;

			var tinted = ClayLook.HsvToRgb( th,
				Math.Clamp( ts * satRatio, 0f, 1f ),
				Math.Clamp( tv * valRatio, 0f, 1f ) );
			brushes[i].Color = tinted.WithAlpha( original.a );
		}
	}

	void ApplyOriginals()
	{
		var brushes = Sculpture.Brushes;
		int n = Math.Min( brushes.Count, OriginalColors.Count );
		for ( int i = 0; i < n; i++ )
			brushes[i].Color = OriginalColors[i];
	}

	static string Hex( Color c ) =>
		$"#{(int)(Math.Clamp( c.r, 0f, 1f ) * 255):x2}{(int)(Math.Clamp( c.g, 0f, 1f ) * 255):x2}{(int)(Math.Clamp( c.b, 0f, 1f ) * 255):x2}";

	// A colour's position on the chroma disc (radius = saturation, angle = hue) plus its value. Greys
	// collapse to the disc centre, so hue differences between them cost nothing — exactly what we want.
	static (float x, float y, float v) ChromaPoint( Color c )
	{
		var (h, s, v) = ClayLook.RgbToHsv( c );
		float rad = h * (MathF.PI / 180f);
		return (s * MathF.Cos( rad ), s * MathF.Sin( rad ), v);
	}

	// Re-detecting shouldn't nuke hand-filled palettes: carry a palette over when an old group's detected
	// colour is close (chroma disc + value, same tolerances) to the new group's.
	List<Color> RescueTints( List<PropColorGroup> oldGroups, Color detected )
	{
		if ( oldGroups is null )
			return new List<Color>();

		var (x, y, v) = ChromaPoint( detected );
		foreach ( var old in oldGroups )
		{
			if ( old.Tints is not { Count: > 0 } )
				continue;
			var (ox, oy, ov) = ChromaPoint( old.Detected );
			float dx = x - ox, dy = y - oy;
			if ( MathF.Sqrt( dx * dx + dy * dy ) <= ChromaTolerance && MathF.Abs( v - ov ) <= ValueTolerance )
				return new List<Color>( old.Tints );
		}
		return new List<Color>();
	}

	bool ResolveSculpture()
	{
		Sculpture ??= GameObject.Components.Get<SdfSculpture>();
		if ( Sculpture.IsValid() )
			return true;
		Log.Warning( "Prop Color Randomizer: no SdfSculpture assigned (or on this object)." );
		return false;
	}

	bool SnapshotValid() =>
		Sculpture.IsValid() && OriginalColors is { Count: > 0 } && Sculpture.AuthoredBrushCount == DetectedBrushCount;

	bool RequireValidSnapshot()
	{
		if ( Groups is not { Count: > 0 } || OriginalColors is not { Count: > 0 } )
		{
			Log.Warning( "Prop Color Randomizer: no groups detected yet — press Detect Groups first." );
			return false;
		}
		if ( Sculpture.AuthoredBrushCount != DetectedBrushCount )
		{
			Log.Warning( $"Prop Color Randomizer: brush list changed since detection ({Sculpture.AuthoredBrushCount} authored now, {DetectedBrushCount} at detect) — re-run Detect Groups." );
			return false;
		}
		return true;
	}
}
